# Generated by Django 3.2.15 on 2022-11-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='designe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='название', max_length=30, verbose_name='Название')),
                ('pub_date', models.DateField(verbose_name='Дата публикации')),
            ],
        ),
    ]
