# Generated by Django 4.1.3 on 2022-11-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designe',
            name='image',
            field=models.ImageField(default='SOME STRING', upload_to='images'),
        ),
    ]
