# Generated by Django 3.2.16 on 2022-11-20 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 20, 17, 22, 9, 986422), null=True, verbose_name='Дата'),
        ),
    ]
