# Generated by Django 3.2.16 on 2022-11-20 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_design_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='design',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 20, 19, 25, 0, 426837), null=True, verbose_name='Дата'),
        ),
    ]
