# Generated by Django 3.2.15 on 2022-11-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_designe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='designe',
            name='info',
            field=models.CharField(help_text='Введите описание', max_length=50, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='designe',
            name='image',
            field=models.ImageField(default='SOME STRING', upload_to='images', verbose_name='Изображение'),
        ),
    ]
