# Generated by Django 3.2.15 on 2022-11-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20221109_1656'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='designe',
            new_name='design',
        ),
    ]
