# Generated by Django 3.2.16 on 2022-11-22 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20221120_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 22, 10, 45, 5, 555649), null=True, verbose_name='Дата'),
        ),
    ]
