# Generated by Django 3.2.15 on 2022-11-15 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_designe_design'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='design',
            name='category',
            field=models.CharField(choices=[('sketch', 'Эскиз'), ('2_D', '2D'), ('3_D', '3D')], default='Эскиз', help_text='Категории', max_length=30, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='design',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 15, 17, 9, 35, 98833)),
        ),
        migrations.AddField(
            model_name='design',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('load', 'Принято в работу'), ('ready', 'Выполнено')], default='new', help_text='Статус', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.ImageField(default='SOME STRING', null=True, upload_to='images', verbose_name='Изображение'),
        ),
    ]
