# Generated by Django 3.2.15 on 2022-11-15 10:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0005_auto_20221115_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='comment',
            field=models.TextField(blank=True, max_length=400, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='design',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='design',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 15, 17, 45, 36, 914815), null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.ImageField(default='SOME STRING', upload_to='images', verbose_name='Изображение'),
        ),
    ]
