# Generated by Django 3.2.15 on 2022-11-15 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20221115_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 15, 19, 54, 8, 406802), null=True),
        ),
    ]
