# Generated by Django 3.2.16 on 2022-11-22 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20221122_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='comment',
            field=models.TextField(max_length=400, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='design',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 22, 16, 35, 46, 962348), null=True, verbose_name='Дата'),
        ),
    ]
