# Generated by Django 4.2.5 on 2023-09-06 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20221122_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 6, 21, 37, 43, 294509), null=True, verbose_name='Дата'),
        ),
    ]
