# Generated by Django 3.2.15 on 2022-11-15 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_design_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 15, 20, 21, 33, 354103), null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Изображение'),
        ),
    ]
