# Generated by Django 3.2.15 on 2022-11-16 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20221115_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='design',
            options={'verbose_name': "blog's item", 'verbose_name_plural': 'blog'},
        ),
        migrations.AlterField(
            model_name='design',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 16, 13, 52, 6, 853710), null=True),
        ),
    ]
