# Generated by Django 3.2.15 on 2022-11-16 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20221116_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='design',
            options={},
        ),
        migrations.AlterField(
            model_name='design',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 16, 14, 24, 53, 355124), null=True),
        ),
    ]
