# Generated by Django 3.2.15 on 2022-11-17 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20221116_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 17, 17, 2, 15, 109575), null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='name',
            field=models.CharField(help_text='название', max_length=30, unique=True, verbose_name='Название'),
        ),
    ]
