# Generated by Django 3.2.16 on 2022-11-18 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20221117_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='design',
            options={'verbose_name': 'Заявку', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='design',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 18, 7, 3, 11, 264253), null=True, verbose_name='Дата'),
        ),
    ]
