# Generated by Django 3.2.15 on 2022-11-18 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20221118_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='ready_images',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Готовый дизайн'),
        ),
        migrations.AlterField(
            model_name='design',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 18, 18, 21, 51, 633271), null=True, verbose_name='Дата'),
        ),
    ]
