# Generated by Django 3.2.15 on 2022-11-18 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20221118_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 18, 18, 40, 27, 532800), null=True, verbose_name='Дата'),
        ),
    ]
