# Generated by Django 3.2.15 on 2022-11-18 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_design_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 18, 18, 55, 33, 190446), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='design',
            name='ready_images',
            field=models.ImageField(blank=True, upload_to='ready/', verbose_name='Готовый дизайн'),
        ),
    ]
