# Generated by Django 3.2.15 on 2022-11-19 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20221118_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='ready_images',
        ),
        migrations.AlterField(
            model_name='design',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 19, 17, 19, 52, 362814), null=True, verbose_name='Дата'),
        ),
    ]
